#!/usr/bin/env bash
# Script to create venv
# Author: Michael Noronha

mkvenv () {
    local OPTIND PYTHON VENVNAME

    if [ -z "$1" ]; then
        echo "mkvenv requires virtualenv name, aborting"
        return 1
    else
        PYTHON=""
        VENVNAME=""

        while [ $# -gt 0  ]; do
            OPTIND=1

            while getopts p: opt; do
                case "$opt" in
                p)  PYTHON=${OPTARG}
                    ;;
                esac
            done

            shift $((OPTIND-1))

            if ! [ -z "$1" ]; then
                VENVNAME="$1"
                shift
            fi
        done


        if [ -z "$VENVNAME" ]; then
            echo "mkvenv requires virtualenv name, aborting"
            return 1
        else
            VENVPATH=$HOME/.virtualenvs/$VENVNAME
            if [ -d "$VENVPATH" ]; then
                echo "A virtual environment named $VENVNAME already exists, aborting."
                return 1
            fi

            if ! [ -z "$PYTHON" ]; then
                virtualenv "$VENVPATH" -p "$PYTHON"
            else
                virtualenv "$VENVPATH"
            fi

            if [ "$?" -eq 0 ]; then
                echo "Created virtual environment $VENVNAME"
                workon "$VENVNAME"

                if [ "$?" -eq 0 ]; then
                    echo "Activated!"
                    return 0
                fi
            fi

            echo "An error occured. Try checking $VENVDIR for oddities."
        fi
    fi
}
