#!/usr/bin/env bash
# Script to delete venv
# Author: Michael Noronha

rmvenv () {
    if [ -z "$1" ]; then
        echo "rmvenv requires at least one virtualenv name, aborting"
        return 1
    else
        for venvname in "$@"
        do
            if [[ "$VIRTUAL_ENV" == "$HOME"/.virtualenvs/"$venvname" ]]
            then
                  deactivate
            fi

            rm -rf "$HOME"/.virtualenvs/"$venvname"

            echo "Removed virtualenv $venvname"
        done
    fi
}
